# Generated by Django 4.2.7 on 2024-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0002_medicinedetails_delete_signupform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
